<?php

return [

    'name' => 'Lemonwares Technology',
    'short_name' => 'Lemonwares',
    'domain' => 'lemonwares.com',
    'url' => env('APP_URL', 'https://lemonwares.com'),
    'tagline' => 'Hosting · Email · Web & Mobile',
    'years_experience' => 12,

    'locales' => [
        'en' => 'English',
        'fr' => 'Français',
        'de' => 'Deutsch',
    ],

    'currency' => [
        'primary' => 'USD',
        'secondary' => 'NGN',
        // Fallback only. Live rate is fetched from open.er-api.com and cached hourly.
        'usd_to_ngn' => (float) env('USD_TO_NGN', 7800),
    ],

    'billing_cycles' => [
        'monthly' => [
            'key' => 'monthly',
            'months' => 1,
            'discount_percent' => 0,
            'whmcs' => 'monthly',
        ],
        'bimonthly' => [
            'key' => 'bimonthly',
            'months' => 2,
            'discount_percent' => 5,
            'whmcs' => 'monthly',
        ],
        'quarterly' => [
            'key' => 'quarterly',
            'months' => 3,
            'discount_percent' => 10,
            'whmcs' => 'quarterly',
        ],
        'annually' => [
            'key' => 'annually',
            'months' => 12,
            'discount_percent' => 20,
            'whmcs' => 'annually',
        ],
    ],

    'whmcs' => [
        'base_url' => rtrim(env('WHMCS_BASE_URL', 'https://billing.lemonwares.com'), '/'),
        'client_login_url' => env('WHMCS_CLIENT_LOGIN_URL', 'https://billing.lemonwares.com/clientarea.php'),
        'order_route' => env('WHMCS_ORDER_ROUTE', '/cart.php'),
        'api_identifier' => env('WHMCS_API_IDENTIFIER', ''),
        'api_secret' => env('WHMCS_API_SECRET', ''),
    ],

    'hosting_plans' => [
        'cpanel' => [
            'slug' => 'cpanel',
            'name' => 'cPanel',
            'title' => 'Cloud Hosting Powered by cPanel',
            'summary' => 'Easy-to-use hosting for websites, blogs, portfolios, and business landing pages.',
            'checkout_provider' => 'whmcs',
            'highlights' => [
                'cPanel control panel',
                'SSL security',
                'Business email support',
                'WordPress toolkit',
                '24/7 expert support',
                'Great for small and medium businesses',
            ],
            'ui_tone' => 'rose',
            'whmcs_pid' => env('WHMCS_PID_CPANEL', ''),
            'specifications' => [
                [
                    'key' => 'starter',
                    'label' => 'Starter',
                    'default_price' => 5,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'Great for small websites and landing pages.',
                    'storage' => '15 GB SSD',
                    'bandwidth' => 'Unmetered',
                    'websites' => '1 website',
                    'highlights' => [
                        'cPanel control panel',
                        'Free SSL certificate',
                        'Daily backups',
                    ],
                    'details' => [
                        'best_for' => 'Personal sites, portfolios, and early-stage business landing pages.',
                        'includes' => [
                            '1 hosted website',
                            'Business email ready',
                            'WordPress one-click install',
                            '24/7 support',
                        ],
                    ],
                ],
                [
                    'key' => 'business',
                    'label' => 'Business',
                    'default_price' => 12,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'Balanced resources for business websites and blogs.',
                    'storage' => '40 GB SSD',
                    'bandwidth' => 'Unmetered',
                    'websites' => 'Up to 5 websites',
                    'highlights' => [
                        'More storage & bandwidth',
                        'Multiple site hosting',
                        'Priority support queue',
                    ],
                    'details' => [
                        'best_for' => 'Growing businesses running blogs, company sites, and client portfolios.',
                        'includes' => [
                            'Up to 5 hosted websites',
                            'Enhanced backup retention',
                            'Staging-friendly resources',
                            '24/7 expert support',
                        ],
                    ],
                ],
                [
                    'key' => 'pro',
                    'label' => 'Pro',
                    'default_price' => 24,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'Higher performance for heavier traffic and ecommerce.',
                    'storage' => '80 GB SSD',
                    'bandwidth' => 'Unmetered',
                    'websites' => 'Unlimited websites',
                    'highlights' => [
                        'Highest shared performance',
                        'Ecommerce-ready resources',
                        'Advanced backup options',
                    ],
                    'details' => [
                        'best_for' => 'Online stores, high-traffic sites, and teams running multiple properties.',
                        'includes' => [
                            'Unlimited hosted websites',
                            'Optimized for WooCommerce & WordPress',
                            'Higher concurrent visitor capacity',
                            'Priority 24/7 support',
                        ],
                    ],
                ],
            ],
        ],
        'plesk' => [
            'slug' => 'plesk',
            'name' => 'Plesk',
            'title' => 'Cloud Hosting Powered by Plesk',
            'summary' => 'Modern shared hosting for businesses that prefer a clean, flexible hosting dashboard.',
            'checkout_provider' => 'whmcs',
            'highlights' => [
                'Plesk control panel',
                'SSL security',
                'Business email support',
                'Node.js & Next.js ready',
                'WordPress ready',
                '24/7 expert support',
            ],
            'ui_tone' => 'blush',
            'whmcs_pid' => env('WHMCS_PID_PLESK', ''),
            'specifications' => [
                [
                    'key' => 'web-basic',
                    'label' => 'Web Basic',
                    'default_price' => 6,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'Ideal for static and CMS websites on Plesk.',
                    'storage' => '20 GB SSD',
                    'bandwidth' => 'Unmetered',
                    'websites' => '1 website',
                    'highlights' => [
                        'Plesk control panel',
                        'Node.js & PHP ready',
                        'Free SSL certificate',
                    ],
                    'details' => [
                        'best_for' => 'Brochure sites, CMS builds, and lightweight web apps on Plesk.',
                        'includes' => [
                            '1 hosted website',
                            'Git deployment support',
                            'WordPress & Next.js ready',
                            '24/7 support',
                        ],
                    ],
                ],
                [
                    'key' => 'web-plus',
                    'label' => 'Web Plus',
                    'default_price' => 14,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'More resources for growing business web apps.',
                    'storage' => '50 GB SSD',
                    'bandwidth' => 'Unmetered',
                    'websites' => 'Up to 5 websites',
                    'highlights' => [
                        'Higher compute headroom',
                        'Multiple app hosting',
                        'Enhanced backup retention',
                    ],
                    'details' => [
                        'best_for' => 'Teams shipping business apps, APIs, and multi-site Plesk deployments.',
                        'includes' => [
                            'Up to 5 hosted websites',
                            'Node.js runtime support',
                            'Database-friendly resources',
                            'Priority support queue',
                        ],
                    ],
                ],
                [
                    'key' => 'web-scale',
                    'label' => 'Web Scale',
                    'default_price' => 28,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'For larger deployments and higher concurrent usage.',
                    'storage' => '100 GB SSD',
                    'bandwidth' => 'Unmetered',
                    'websites' => 'Unlimited websites',
                    'highlights' => [
                        'Top-tier shared performance',
                        'High concurrent traffic',
                        'Production-grade backups',
                    ],
                    'details' => [
                        'best_for' => 'Demanding web apps, SaaS frontends, and high-traffic business platforms.',
                        'includes' => [
                            'Unlimited hosted websites',
                            'Advanced Plesk tooling',
                            'Higher PHP & Node.js limits',
                            'Priority 24/7 support',
                        ],
                    ],
                ],
            ],
        ],
        'vps' => [
            'slug' => 'vps',
            'name' => 'AMD EPYC',
            'title' => 'VPS Root Server',
            'summary' => 'Dedicated server resources for businesses that need more power, control, and scalability.',
            'checkout_provider' => 'internal',
            'highlights' => [
                'Root access',
                'Better performance',
                'Scalable server resources',
                '24/7 expert support',
                'Suitable for apps and high-traffic sites',
                'For developers and advanced users',
            ],
            'ui_tone' => 'slate',
            'whmcs_pid' => env('WHMCS_PID_VPS', ''),
            'specifications' => [
                [
                    'key' => 'vps-2',
                    'label' => 'VPS 2',
                    'default_price' => 18,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'Entry VPS for lightweight production workloads.',
                    'cpu' => '2 vCPU',
                    'ram' => '4 GB RAM',
                    'storage' => '80 GB NVMe',
                    'highlights' => [
                        'Full root access',
                        'AMD EPYC processors',
                        'Dedicated resources',
                    ],
                    'details' => [
                        'best_for' => 'Side projects, staging environments, and small production apps.',
                        'includes' => [
                            'Root / SSH access',
                            'NVMe storage',
                            'Custom stack installation',
                            '24/7 expert support',
                        ],
                    ],
                ],
                [
                    'key' => 'vps-4',
                    'label' => 'VPS 4',
                    'default_price' => 36,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'Balanced VPS for medium traffic services.',
                    'cpu' => '4 vCPU',
                    'ram' => '8 GB RAM',
                    'storage' => '160 GB NVMe',
                    'highlights' => [
                        'Balanced CPU & memory',
                        'Ideal for APIs & apps',
                        'Scalable architecture',
                    ],
                    'details' => [
                        'best_for' => 'Business APIs, Docker workloads, and medium-traffic web services.',
                        'includes' => [
                            'Root / SSH access',
                            'Higher I/O performance',
                            'Database-friendly RAM',
                            'Priority support queue',
                        ],
                    ],
                ],
                [
                    'key' => 'vps-8',
                    'label' => 'VPS 8',
                    'default_price' => 72,
                    'default_currency' => 'USD',
                    'default_billing_cycle' => 'monthly',
                    'default_suffix' => '/mo',
                    'description' => 'High-performance VPS for heavy applications.',
                    'cpu' => '8 vCPU',
                    'ram' => '16 GB RAM',
                    'storage' => '320 GB NVMe',
                    'highlights' => [
                        'Maximum VPS performance',
                        'Heavy workload ready',
                        'Enterprise-grade headroom',
                    ],
                    'details' => [
                        'best_for' => 'High-traffic platforms, multi-service stacks, and resource-intensive apps.',
                        'includes' => [
                            'Root / SSH access',
                            '320 GB NVMe storage',
                            'High concurrent processing',
                            'Priority 24/7 support',
                        ],
                    ],
                ],
            ],
        ],
    ],

    'services' => [
        [
            'key' => 'hosting',
            'image' => 'images/services/hosting.jpg',
            'icon' => 'zap',
            'tone' => 'slate',
        ],
        [
            'key' => 'email',
            'image' => 'images/services/email.jpg',
            'icon' => 'mail',
            'tone' => 'blush',
        ],
        [
            'key' => 'web',
            'image' => 'images/services/web.jpg',
            'icon' => 'code',
            'tone' => 'slate',
        ],
        [
            'key' => 'mobile',
            'image' => 'images/services/mobile.jpg',
            'icon' => 'smartphone',
            'tone' => 'rose',
        ],
        [
            'key' => 'support',
            'image' => 'images/services/support.jpg',
            'icon' => 'headset',
            'tone' => 'blush',
        ],
    ],

    'email' => 'hello@lemonwares.com',
    'phone' => '+234 906 732 2844',
    'phone_e164' => '+2349067322844',
    'whatsapp' => 'https://wa.me/2349067322844',

    'address' => '26, Akin Leigh Crescent, Lekki Phase 1, Lagos, Nigeria.',

    'social' => [
        ['label' => 'LinkedIn', 'href' => 'https://linkedin.com', 'icon' => 'linkedin'],
        ['label' => 'Facebook', 'href' => 'https://facebook.com', 'icon' => 'facebook'],
        ['label' => 'Instagram', 'href' => 'https://instagram.com', 'icon' => 'instagram'],
    ],

    'technologies' => [
        ['name' => 'JavaScript', 'logo' => 'images/tech/javascript.svg'],
        ['name' => 'TypeScript', 'logo' => 'images/tech/typescript.svg'],
        ['name' => 'Python', 'logo' => 'images/tech/python.svg'],
        ['name' => 'Node.js', 'logo' => 'images/tech/nodejs.svg'],
        ['name' => 'React', 'logo' => 'images/tech/react.svg'],
        ['name' => 'Next.js', 'logo' => 'images/tech/nextjs.svg'],
        ['name' => 'Vite', 'logo' => 'images/tech/vite.svg'],
        ['name' => 'React Native', 'logo' => 'images/tech/reactnative.svg'],
        ['name' => 'PWA', 'logo' => 'images/tech/pwa.svg'],
        ['name' => 'PHP', 'logo' => 'images/tech/php.svg'],
        ['name' => 'Laravel', 'logo' => 'images/tech/laravel.svg'],
        ['name' => 'WordPress', 'logo' => 'images/tech/wordpress.svg'],
        ['name' => 'PostgreSQL', 'logo' => 'images/tech/postgresql.svg'],
        ['name' => 'MySQL', 'logo' => 'images/tech/mysql.svg'],
        ['name' => 'MongoDB', 'logo' => 'images/tech/mongodb.svg'],
        ['name' => 'Flutter', 'logo' => 'images/tech/flutter.svg'],
        ['name' => 'CMS', 'logo' => null],
    ],

    'partners' => [
        ['name' => 'Restination Apt', 'meta' => 'Web Development', 'href' => '/case-studies'],
        ['name' => 'Bright Media', 'meta' => 'WordPress Hosting', 'href' => '/case-studies'],
        ['name' => 'Field Service App', 'meta' => 'Mobile Development', 'href' => '/case-studies'],
        ['name' => 'VPS Migration', 'meta' => 'Infrastructure', 'href' => '/case-studies'],
    ],

    'country_options' => [
        'NG' => 'Nigeria',
        'GH' => 'Ghana',
        'KE' => 'Kenya',
        'ZA' => 'South Africa',
        'EG' => 'Egypt',
        'MA' => 'Morocco',
        'RW' => 'Rwanda',
        'TZ' => 'Tanzania',
        'UG' => 'Uganda',
        'CM' => 'Cameroon',
        'CI' => "Cote d'Ivoire",
        'SN' => 'Senegal',
        'US' => 'United States',
        'CA' => 'Canada',
        'MX' => 'Mexico',
        'BR' => 'Brazil',
        'AR' => 'Argentina',
        'GB' => 'United Kingdom',
        'IE' => 'Ireland',
        'FR' => 'France',
        'DE' => 'Germany',
        'NL' => 'Netherlands',
        'ES' => 'Spain',
        'IT' => 'Italy',
        'PT' => 'Portugal',
        'SE' => 'Sweden',
        'NO' => 'Norway',
        'DK' => 'Denmark',
        'AE' => 'United Arab Emirates',
        'SA' => 'Saudi Arabia',
        'QA' => 'Qatar',
        'IN' => 'India',
        'PK' => 'Pakistan',
        'BD' => 'Bangladesh',
        'CN' => 'China',
        'JP' => 'Japan',
        'KR' => 'South Korea',
        'SG' => 'Singapore',
        'MY' => 'Malaysia',
        'AU' => 'Australia',
        'NZ' => 'New Zealand',
    ],

];
